management:
  security:
    enabled: false
server:
  contextPath: /v1
fw_appId: samplerest
RESTAuthFilterConfig:
  filterUrls:
    - /samplerest/*
---

logging:
  level:
    com.telus.selfserve.services.logging: DEBUG
    root: INFO
spring.jackson.default-property-inclusion: NON_NULL
spring.jackson.serialization.write-dates-as-timestamps: false
spring.jackson.date-format: yyyy-MM-dd'T'HH:mm:ssZ

service:
    common:
      username: APP_SELFSERVEUSGBIZSVC
      password: soaorgid

management:   
  metrics:
    distribution:
      percentiles:
        "[http.server.requests]": 0.95, 0.99
      percentiles-histogram:
        "[http.server.requests]": true
        
endpoints.prometheus.enabled: true
      
---

spring:
  profiles: local
    
service:
  common:
    hosts:
      laird: https://soa-mp-laird-pt148.tsl.telus.com


---